-- Create tables if they do not exist

CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    passwd TEXT NOT NULL DEFAULT '',
    hash TEXT NOT NULL,
    x INTEGER NOT NULL DEFAULT 10,
    y INTEGER NOT NULL DEFAULT 10,
    dir INTEGER NOT NULL DEFAULT 0,
    health INTEGER NOT NULL DEFAULT 100,
    max_health INTEGER NOT NULL DEFAULT 100,
    money INTEGER NOT NULL DEFAULT 1000,
    creds INTEGER NOT NULL DEFAULT 0,
    skin INTEGER NOT NULL DEFAULT 0,
    auto_dig INTEGER NOT NULL DEFAULT 0,
    cry_green INTEGER NOT NULL DEFAULT 0,
    cry_blue INTEGER NOT NULL DEFAULT 0,
    cry_red INTEGER NOT NULL DEFAULT 0,
    cry_violet INTEGER NOT NULL DEFAULT 0,
    cry_white INTEGER NOT NULL DEFAULT 0,
    cry_cyan INTEGER NOT NULL DEFAULT 0,
    clan_id INTEGER DEFAULT NULL,
    clan_rank INTEGER NOT NULL DEFAULT 0,
    resp_x INTEGER DEFAULT NULL,
    resp_y INTEGER DEFAULT NULL,
    inventory TEXT NOT NULL DEFAULT '{}',
    skills TEXT NOT NULL DEFAULT '{}',
    role INTEGER NOT NULL DEFAULT 0,
    chat_color INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS chats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tag TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

INSERT OR IGNORE INTO chats (tag, name) VALUES ('FED', 'Федеральный чат');
INSERT OR IGNORE INTO chats (tag, name) VALUES ('DNO', 'Дно');

CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    chat_tag TEXT NOT NULL,
    player_name TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch()),
    player_id INTEGER NOT NULL DEFAULT 0,
    color INTEGER NOT NULL DEFAULT 10
);

CREATE TABLE IF NOT EXISTS lines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    playerid INTEGER NOT NULL DEFAULT 0,
    message TEXT NOT NULL DEFAULT '',
    chat_tag TEXT NOT NULL DEFAULT 'FED'
);

CREATE TABLE IF NOT EXISTS buildings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type_code TEXT NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    owner_id INTEGER NOT NULL DEFAULT 0,
    clan_id INTEGER NOT NULL DEFAULT 0,
    data TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS clans (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    abr TEXT NOT NULL,
    owner_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS clan_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    clan_id INTEGER NOT NULL,
    player_id INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS clan_invites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    clan_id INTEGER NOT NULL,
    player_id INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(clan_id, player_id)
);

CREATE TABLE IF NOT EXISTS programs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    FOREIGN KEY(player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS boxes (
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    ze INTEGER NOT NULL DEFAULT 0,
    cr INTEGER NOT NULL DEFAULT 0,
    si INTEGER NOT NULL DEFAULT 0,
    be INTEGER NOT NULL DEFAULT 0,
    fi INTEGER NOT NULL DEFAULT 0,
    go INTEGER NOT NULL DEFAULT 0,
    cry_green INTEGER NOT NULL DEFAULT 0,
    cry_blue INTEGER NOT NULL DEFAULT 0,
    cry_red INTEGER NOT NULL DEFAULT 0,
    cry_violet INTEGER NOT NULL DEFAULT 0,
    cry_white INTEGER NOT NULL DEFAULT 0,
    cry_cyan INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (x, y)
);
