//! Definitions of all `PlayerCommand`, `GameEvent`, and `SaveCommand` contracts.
//! These enums decouple the network session tasks, the ECS game loop thread,
//! and the asynchronous database persistence writer task.

use bytes::Bytes;
use openmines_shared::db::buildings::BuildingRow;
use openmines_shared::db::chats::ChatRow;
use openmines_shared::db::clans::ClanRow;
use openmines_shared::db::orders::OrderRow;
use openmines_shared::db::players::PlayerRow;
use openmines_shared::db::programs::ProgramRow;
use openmines_shared::protocol::Packet;

/// `PlayerId` is a type alias for the unique i32 identifying a player.
#[allow(dead_code)]
type PlayerId = i32;

/// All incoming action commands from client sessions to the game tick loop.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum PlayerCommand {
    /// Initial connection handshake and registration.
    Connect {
        player_id: PlayerId,
        username: String,
        token: String,
    },
    /// Clean disconnect of the player session.
    Disconnect { player_id: PlayerId, token: String },
    /// Pong response returning client time.
    Pong {
        player_id: PlayerId,
        response: String,
        time: String,
    },
    /// Player movement request.
    Move {
        player_id: PlayerId,
        time: u32,
        x: i32,
        y: i32,
        direction: i32,
        programmatic: bool,
    },
    /// Cell digging action request.
    Dig {
        player_id: PlayerId,
        direction: i32,
        programmatic: bool,
    },
    /// Construction or block placement request.
    Build {
        player_id: PlayerId,
        direction: i32,
        block_type: String,
        programmatic: bool,
    },
    /// Geology scan action request.
    Geology {
        player_id: PlayerId,
        programmatic: bool,
    },
    /// Health self-healing request.
    Heal {
        player_id: PlayerId,
        programmatic: bool,
    },
    /// GUI button click action.
    GuiButton { player_id: PlayerId, button: String },
    /// Local area chat message.
    LocalChat {
        player_id: PlayerId,
        message: String,
    },
    /// Global channel chat message.
    ChannelChat { player_id: PlayerId, payload: Bytes },
    /// Request to resynchronize chat history.
    ChatResync { player_id: PlayerId, payload: Bytes },
    /// Chat navigation/channel menu interaction.
    ChatMenu { player_id: PlayerId, payload: Bytes },
    /// Join or select chat channel.
    ChatChoose { player_id: PlayerId, payload: Bytes },
    /// Update individual chat settings.
    ChatSettings { player_id: PlayerId, payload: Bytes },
    /// Send a private chat message to a user.
    ChatPrivate { player_id: PlayerId, payload: Bytes },
    /// Request nicknames for a list of player IDs.
    Whois { player_id: PlayerId, ids: Vec<i32> },
    /// Toggle automatic digging status.
    ToggleAutoDig { player_id: PlayerId },
    /// Toggle player aggression status.
    ToggleAggression { player_id: PlayerId },
    /// Select item index in player inventory.
    InventoryChoose { player_id: PlayerId, payload: Bytes },
    /// Use currently selected inventory item.
    InventoryUse { player_id: PlayerId },
    /// Toggle inventory GUI visibility.
    InventoryToggle { player_id: PlayerId },
    /// Open a nearby box / chest.
    OpenBox { player_id: PlayerId },
    /// Claim daily connection reward.
    ClaimBonus { player_id: PlayerId },
    /// Save client settings payload.
    SettingsSave { player_id: PlayerId, payload: Bytes },
    /// Trigger admin command GUI or panels.
    AdminAction { player_id: PlayerId },
    /// Respawn player after death.
    Respawn { player_id: PlayerId },
    /// Open the programmer program editing GUI.
    OpenProgrammer { player_id: PlayerId },
    /// Request list of building structures owned by the player.
    RequestMyBuildings { player_id: PlayerId },
    /// Open clan management GUI.
    OpenClan { player_id: PlayerId },
    /// Programmator program lifecycle action (save, delete, restart, rename, copy).
    ProgramAction {
        player_id: PlayerId,
        event: String,
        payload: Bytes,
    },
}

/// All outbound events generated by the game engine loop sent to players or broadcasted.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum GameEvent {
    /// Send a packet privately to a single connected player session.
    SendPrivate { player_id: PlayerId, packet: Packet },
    /// Broadcast a packet to all active player sessions.
    Broadcast { packet: Packet },
    /// Force-disconnect a player session due to gameplay reasons (e.g. kicked, banned).
    Disconnect { player_id: PlayerId, reason: String },
}

/// All database write transactions sent from the game thread to the persistence worker.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum SaveCommand {
    /// Save or update player statistics, inventory, positions, and skills.
    SavePlayer { row: Box<PlayerRow> },
    /// Create or update a map building structure.
    SaveBuilding { row: Box<BuildingRow> },
    /// Delete a map building structure.
    DeleteBuilding { id: i32 },
    /// Create or update clan parameters.
    SaveClan { row: ClanRow },
    /// Delete a clan from the game database.
    DeleteClan { id: i32 },
    /// Save a newly sent chat message to persistent history.
    SaveChatMessage { row: ChatRow },
    /// Create or update a programmer script program.
    SaveProgram { row: ProgramRow },
    /// Delete a programmer script program.
    DeleteProgram { id: i32 },
    /// Create or update a market order.
    SaveOrder { row: OrderRow },
    /// Delete a completed or cancelled market order.
    DeleteOrder { id: i32 },
}
